void greeting();
int input(double *k1, double *k2, double *k3);
void failedInput();
int isequal(double x, double y);
int solve(double k1, double k2, double k3, double *s1, double *s2);
int linearSolve(double k2, double k3, double *s1);
int squareSolve(double k1, double k2, double k3, double *s1, double *s2);
void output(int roots, double s1, double s2);
void nextEquation(char *sym);
void goodbye();
